version: 0
ingredients:
  - type: ""
    is-scalable: false
    amount: 0
    name: Ice
  - type: Volume
    amount: 29.5734997
    name: Bailey's Irish Cream
  - type: Volume
    amount: 29.5734997
    name: Vodka
  - type: Volume
    amount: 29.5734997
    name: Creme de Cacao
  - type: ""
    is-scalable: false
    amount: 0
    name: Chocolate Sauce
  - type: ""
    is-scalable: false
    amount: 0
    name: Dark Chocolate
    note: grated
directions:
  - Add Bailey's, Vodka, and Creme de Cacao into shaker with ice.
  - Dress cocktail glass with chocolate sauce.
  - Shake ingredients and strain into glass.
  - Grate dark chocolate on top.