version: 0
ingredients:
  - type: ""
    is-scalable: false
    amount: 0
    name: Ice
  - type: Volume
    amount: 29.5734997
    name: Vodka
  - type: Volume
    amount: 29.5734997
    name: Triple Sec
  - type: Volume
    amount: 22.1801243
    name: Lime Juice
  - type: Wheel/Wedge/Twist
    is-scalable: false
    amount: 0
    name: "Lime "
    note: for garnish
directions:
  - Combine vodka, triple sec, and lime juice in a shaker with ice.
  - Strain into two 1.5oz shot glasses, or a small rocks glass.
  - Garnish with lime wheels, wedges, or twists.
notes: Makes 2x 1.5oz or 3x 1oz shots.