version: 0
ingredients:
  - type: ""
    is-scalable: false
    amount: 0
    name: Ice
  - type: Volume
    amount: 59.1469994
    name: Tequila Blanco
  - type: Volume
    amount: 22.1801243
    name: Lime Juice
  - type: Pumps
    is-scalable: true
    amount: 2
    name: "Ginger Syrup "
  - type: Volume
    amount: 11.0900621
    name: Honey Syrup
  - type: ""
    is-scalable: false
    amount: 0
    name: Candied Ginger
    note: for garnish
  - type: ""
    is-scalable: false
    amount: 0
    name: Mezcal
directions:
  - Add scotch, lemon juice, ginger syrup, and honey syrup into shaker with ice.
  - Strain into rocks glass
  - Add a float of mezcal.
  - Garnish with candied ginger on a toothpick.