version: 0
ingredients:
  - type: ""
    is-scalable: false
    amount: 0
    name: Ice
  - type: Volume
    amount: 14.7867498
    name: White Rum
  - type: Volume
    amount: 14.7867498
    name: Silver Tequila
  - type: Volume
    amount: 14.7867498
    name: Vodka
  - type: Volume
    amount: 14.7867498
    name: Gin
  - type: Volume
    amount: 29.5734997
    name: Lemon Juice
  - type: ""
    is-scalable: false
    amount: 0
    name: Cola
  - type: Wedge/Wheel
    is-scalable: true
    amount: 1
    name: "Lemon "
    note: for garnish
directions:
  - Combine rum, tequila, vodka, gin, triple sec, and lemon juice in a shaker with ice.
  - Strain into a colins glass with new ice.
  - Top with cola and stir
  - Garnish with lemon wheel or wedge.