version: 0
ingredients:
  - type: ""
    is-scalable: false
    amount: 0
    name: Ice
  - type: Volume
    amount: 59.1469994
    name: Bailey's Irish Cream
  - type: Volume
    amount: 29.5734997
    name: Espresso
  - type: Volume
    amount: 9.85783386
    name: Milk
  - type: Beans
    is-scalable: true
    amount: 3
    name: "Espresso "
    note: for garnish
directions:
  - Add Bailey's, Espresso, and Milk into shaker with ice.
  - Strain into cocktail glass
  - Garnish with espresso beans creating a triangle in the center.