version: 0
ingredients:
  - type: ""
    is-scalable: false
    amount: 0
    name: Ice
  - type: Volume
    amount: 29.5734997
    name: Vodka
  - type: Volume
    amount: 29.5734997
    name: Coffee Liqueur
  - type: Volume
    amount: 14.7867498
    name: Simple Syrup
  - type: Volume
    amount: 29.5734997
    name: Espresso
  - type: ""
    is-scalable: true
    amount: 3
    name: Coffee Beans
    note: for garnish
directions:
  - Combine vodka, coffee liqueur, simple syrup, and espresso in a shaker with ice.
  - Shake contents extra hard to create foam.
  - Strain into cocktail glass.
  - Garnish with espresso beans crating a triangle in the center.