version: 0
ingredients:
  - type: ""
    is-scalable: false
    amount: 0
    name: Ice
  - type: Volume
    amount: 29.5734997
    name: Vodka
  - type: Volume
    amount: 29.5734997
    name: Peach Schnappes
  - type: Volume
    amount: 9.85783386
    name: Orange Juice
  - type: Volume
    amount: 19.7156677
    name: Cranberry Cocktail
directions:
  - Combine ingredients in a shaker with ice.
  - Strain into a collins glass over new ice.