version: 1
ingredients:
  - type: Volume
    amount: 59.1470947
    name: Extra Virgin Olive Oil
  - type: Volume
    amount: 59.1470947
    name: Tomato Paste
  - type: Volume
    amount: 236.588379
    name: Tomato Passata
  - type: Cloves
    is-scalable: true
    amount: 1
    name: Garlic
    note: minced
  - type: ""
    is-scalable: true
    amount: 1
    name: Shallots
    note: minced
  - type: Volume
    amount: 4.92892504
    name: Calabrian Chili Oil
  - type: Volume
    amount: 29.5735474
    name: Vodka
  - type: ""
    is-scalable: false
    amount: 0
    name: Salt
  - type: ""
    is-scalable: false
    amount: 0
    name: Pepper
  - type: Mass
    amount: 500
    name: Rigatoni
    note: (or other tubed pasta)
  - type: Volume
    amount: 236.588379
    name: Whipping Cream
  - type: ""
    is-scalable: false
    amount: 0
    name: Parmigiano Reggiano
    note: grated, for garnish
  - type: ""
    is-scalable: false
    amount: 0
    name: Basil Leaves
    note: chopped, for serving
directions:
  - "If adding chicken, prepare Italian cast iron chicken ahead of time and slice into strips. "
  - Bring a pot of water to a boil and cook pasta according to package directions.
  - In a skillet, begin coating the pan with olive oil, followed by garlic, shallot, and chilli oil. Cook around 30 seconds, until aromatic.
  - Add domato paste to break up the pulp, then begin adding the passata and vodka. Let simmer.
  - Add cream and season with salt an pepper to taste.
  - Combine with cooked pasta and garnish with chopped basil and grated parmigiano reggiano