version: 0
ingredients:
  - type: Mass
    amount: 453.591888
    name: Fresh Baby Spinach
  - type: Volume
    amount: 59.1470947
    name: Water
  - type: Volume
    amount: 4.92892504
    name: Olive Oil
  - type: ""
    is-scalable: true
    amount: 1
    name: Medium Tomato
    note: Diced
  - type: Volume
    amount: 4.92892504
    name: Garlic Powder
  - type: Volume
    amount: 4.92892504
    name: Onion Powder
  - type: Volume
    amount: 4.92892504
    name: Garam Masala
    note: (cinnamon, peppercorn, cardamom. mustard seed, cordiander, cloves, nutmeg)
  - type: Volume
    amount: 4.92892504
    name: Jalapeno
    note: finely minced
  - type: Volume
    amount: 2.46446252
    name: Tumeric
  - type: Volume
    amount: 2.46446252
    name: Fresh Ginger
    note: grated
  - type: Volume
    amount: 4.92892504
    name: Salt
  - type: Volume
    amount: 177.441284
    name: Whipping Cream
directions:
  - "In a large Skillet, taste spinach in water over medium-high heat until wilted, 5 minutes. Remove cooked spinach from the pan and set aside to cool (skip this pre-cooking if using frozen spinach). "
  - In the same pan, at the olive oil and reduce heat to medium, then add the tomato, powder, onion powder, garam masala, jalapeno, turmeric, ginger, and salt. Stir and cook for about 5 minutes or until tomato is soft. Using the back of a wooden spoon, ash the Tomato into the bottom of the pan to break it up.
  - Once the precooked spinach has completely cooled, squeeze out any excess water and run a knife through it to chop it up (if using Frozen chopped spinach, saw it and squeeze all the water out of it).
  - "Add the chopped spinach to the pan with the spiced tomato mixture, stir well to combine, and heat through. Reduce heat to low. "
  - Add the whipping cream to the spinach mixture and stir well. Simmer over low heat until mixture is heated through, about 5 minutes. Serve immediately.
notes: Use 10 oz of spinach instead of fresh. Replace whipping cream with coconut Milk/Cream for dairy free.