version: 0
ingredients:
  - type: ""
    is-scalable: true
    amount: 1
    name: Avocado
  - type: Volume
    amount: 14.7868004
    name: Cocoa Powder
  - type: Volume
    amount: 14.7868004
    name: Honey
  - type: ""
    is-scalable: false
    amount: 0
    name: Berries
    note: for garnish
directions:
  - Add avocado, cocoa powder, and honey into a Ziploc bag and crush into pudding consistency.
  - Add to bowl and top with berries.