version: 0
ingredients:
  - type: ""
    is-scalable: false
    amount: 0
    name: Ice
  - type: Volume
    amount: 29.5734997
    name: Coffee Liqueur
  - type: Volume
    amount: 59.1469994
    name: Vodka
  - type: Volume
    amount: 29.5734997
    name: Whipping Cream
directions:
  - Combine ingredients in rocks glass.
notes: No whipping cream for "Black Russian"